export enum MaskFunctionsEnum {
  MultiplyByThousand = 'MultiplyByThousand',
  MultiplyByMillion = 'MultiplyByMillion',
  Absolute = 'Absolute',
  AbsoluteAndDevide = 'AbsoluteAndDevide',
  ReLU = 'ReLU',
  ReLUReverse = 'ReLUReverse',
  ReLUReverseAndDevide = 'ReLUReverseAndDevide',
  BinaryToIp = 'BinaryToIp',
  BinaryToMac = 'BinaryToMac',
  BinaryToString = 'BinaryToString',
  BinaryToUnsignedLittleEndian = 'BinaryToUnsignedLittleEndian',
  BinaryToDate = 'BinaryToDate',
  BinaryUptimeToTimeFormat = 'BinaryUptimeToTimeFormat',
  scaleMOD = 'scaleMOD',
  kelvinToCelsius = 'kelvinToCelsius',
  parseFloatMask = 'parseFloatMask',
  NumberStringToNFixedNumber = 'numberStringToNFixedNumber',
  DecimalToPercentage = 'decimalToPercentage',
  FormatReadableNumber = 'formatReadableNumber',
  DevideTo100 = 'devideTo100',
  DivideByThousand = 'divideByThousand',
  ScaleMehrizMod = 'scaleMehrizMod',
  BinaryToVersion = 'binaryToVersion',
  ScaleModFromBinaryValue = 'scaleModFromBinaryValue',
  ToFixed1 = 'toFixed1',
}
