export enum SettingKeysEnum {
  OtpExpiresAt = 'otpExpiresAt',
  UserOtpAttemptLimit = 'userOtpAttemptLimit',
  UserOtpAttemptTimeWindow = 'userOtpAttemptTimeWindow',
  IpOtpAttemptLimit = 'ipOtpAttemptLimit',
  IpOtpAttemptTimeWindow = 'ipOtpAttemptTimeWindow',
  JwtExpirationSeconds = 'jwtExpirationSeconds',
  OtpVerificationTryCount = 'otpVerificationTryCount',
  RateLimiterTimeWindowPublic = 'rateLimiterTimeWindowPublic',
  RateLimiterLimitPublic = 'rateLimiterLimitPublic',
  RateLimiterLimitPrivate = 'rateLimiterLimitPrivate',
  RateLimiterTimeWindowPrivate = 'rateLimiterTimeWindowPrivate',
  AuthenticatorName = 'authenticatorName',
  AuthenticatorSecretLength = 'authenticatorSecretLength',
  DisabledOtpStaticValue = 'disabledOtpStaticValue',
  PasswordResetTokenExpiresAt = 'passwordResetTokenExpiresAt',
  UserPasswordResetAttemptLimit = 'userPasswordResetAttemptLimit',
  UserPasswordResetAttemptTimeWindow = 'userPasswordResetAttemptTimeWindow',
  IpPasswordResetAttemptLimit = 'ipPasswordResetAttemptLimit',
  IpPasswordResetAttemptTimeWindow = 'ipPasswordResetAttemptTimeWindow',
  PasswordResetVerificationTryCount = 'passwordResetVerificationTryCount',
}
